
--DROP DATABASE DBZERO;
CREATE DATABASE DBZERO;
USE DBZERO;

-- BORRAR TABLAS
--    DROP TABLE PERSONA;
-- BORRAR TABLAS




--DROP TABLE INGRESOS_EGRESOS;
USE DBZERO;
CREATE TABLE INGRESOS_EGRESOS (
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
DETALLE VARCHAR(255),
EGRESOS NUMERIC(18,2),
FECHA DATETIME,
INGRESOS NUMERIC(18,2)
);



--DROP TABLE IMAGEN_PRODUCTO;
USE DBZERO;
CREATE TABLE IMAGEN_PRODUCTO (
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
ARCHIVO VARBINARY(MAX),
IMAGEN VARBINARY(MAX)
);




/*
ALTER TABLE USUARIO ADD CORREO VARCHAR(255);
ALTER TABLE USUARIO DROP COLUMN CORREO;
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_ZAPATO FOREIGN KEY (ZAPATO_ID) REFERENCES ZAPATO(ID);
*/


--DROP TABLE USUARIO;
USE DBZERO;
CREATE TABLE USUARIO (
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL,
NOMBRE_DOS VARCHAR(255),
APELLIDO VARCHAR(255),
APELLIDO_DOS VARCHAR(255),
NOMBRE_COMPLETO VARCHAR(1020),
COMENTARIOS VARCHAR(512),
PENDIENTE_DE_PAGO NUMERIC(18,2)
);





--DROP TABLE PRODUCTO;
USE DBZERO;
CREATE TABLE PRODUCTO (
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(255),
EXISTENCIAS INT,
COSTO_UNIDAD NUMERIC(18,2),
FECHA_ADQUISICION DATETIME,
FECHA_MODIFICADO DATETIME,
GANANCIA NUMERIC(18,2),
PRECIO_VENTA NUMERIC(18,2)
);


-- DROP TABLE PRODUCTO;
USE DBZERO;
CREATE TABLE FACTURA(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
COSTO_TOTAL NUMERIC(18,2),
FECHA_DEVOLUCION DATETIME,
FECHA_EMISION DATETIME,
GANANCIA NUMERIC(18,2),
IVA NUMERIC(18,2),
NOMBRE_COMPLETO VARCHAR(1020),
SUBTOTAL_SIN_IVA NUMERIC(18,2),
TIPO_PAGO VARCHAR(1),
TOTAL NUMERIC(18,2),
USUARIO_ID BIGINT REFERENCES USUARIO(ID)
);





-- DROP TABLE FACTURA_DETALLE;
USE DBZERO;
CREATE TABLE FACTURA_DETALLE (
ID BIGINT IDENTITY(1,1) PRIMARY KEY,

CANTIDAD_PRODUCTO_VENDIDO INT,
COSTO_DEL_SUBTOTAL_POR_PRODUCTO NUMERIC(18,2),

COSTO_UNIDAD NUMERIC(18,2),
GANANCIA_DEL_SUBTOTAL_POR_PRODUCTO NUMERIC(18,2),

GANANCIA_UNIDAD NUMERIC(18,2),
IVA_DEL_SUBTOTAL_POR_PRODUCTO NUMERIC(18,2),

NOMBRE_PRODUCTO VARCHAR(255),
PRECIO_DE_VENTA_POR_PRODUCTO NUMERIC(18,2),

SUBTOTAL_POR_PRODUCTO NUMERIC(18,2),

FACTURA_ID BIGINT REFERENCES FACTURA(ID),
PRODUCTO_ID BIGINT CONSTRAINT FK_FACTURA_DETALLE_PRODUCTO FOREIGN KEY REFERENCES PRODUCTO(ID),
);

















-- DROP TABLE INVENTARIO;
USE DBZERO;
CREATE TABLE INVENTARIO (
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
ENTRADAS INT,
EXISTENCIA INT,
FECHA DATETIME,
SALDO_ANTERIOR INT,
SALIDAS INT,
PRODUCTO_ID BIGINT REFERENCES PRODUCTO(ID)
);





-- DROP TABLE CLIENTE_ABONA;
USE DBZERO;
CREATE TABLE CLIENTE_ABONA (
ID BIGINT IDENTITY(1,1) PRIMARY KEY,

ABONOS NUMERIC(18,2),
CARGOS NUMERIC(18,2),

DETALLES VARCHAR(512),
FECHA DATETIME,

SALDO NUMERIC(18,2),
SALDO_ANTERIOR NUMERIC(18,2),

USUARIO_ID BIGINT REFERENCES USUARIO(ID),
FACTURA_ID BIGINT REFERENCES FACTURA(ID)
);











--END