
CREATE DATABASE INVENTARIO_FACTURACION CHARACTER SET = 'utf8mb4' COLLATE = 'utf8mb4_0900_ai_ci';

USE INVENTARIO_FACTURACION;

CREATE TABLE CLIENTE_ABONA (ABONOS DECIMAL(38,2), CARGOS DECIMAL(38,2), FACTURA_ID INTEGER, ID INTEGER NOT NULL AUTO_INCREMENT, SALDO DECIMAL(38,2), SALDO_ANTERIOR DECIMAL(38,2), USUARIO_ID INTEGER, FECHA DATETIME(6), DETALLES VARCHAR(512), PRIMARY KEY (ID)) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE FACTURA (COSTO_TOTAL DECIMAL(38,2) NOT NULL, GANANCIA DECIMAL(38,2) NOT NULL, ID INTEGER NOT NULL AUTO_INCREMENT, IVA DECIMAL(38,2) NOT NULL, SUBTOTAL_SIN_IVA DECIMAL(38,2) NOT NULL, TIPO_PAGO VARCHAR(1), TOTAL DECIMAL(38,2) NOT NULL, USUARIO_ID INTEGER, FECHA_DEVOLUCION DATETIME(6), FECHA_EMISION DATETIME(6), NOMBRE_COMPLETO VARCHAR(255) NOT NULL, PRIMARY KEY (ID)) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE FACTURA_DETALLE (CANTIDAD_PRODUCTO_VENDIDO INTEGER NOT NULL, COSTO_DEL_SUBTOTAL_POR_PRODUCTO DECIMAL(38,2), COSTO_UNIDAD DECIMAL(38,2), FACTURA_ID INTEGER, GANANCIA_DEL_SUBTOTAL_POR_PRODUCTO DECIMAL(38,2), GANANCIA_UNIDAD DECIMAL(38,2), ID INTEGER NOT NULL AUTO_INCREMENT, IVA_DEL_SUBTOTAL_POR_PRODUCTO DECIMAL(38,2), PRECIO_VENTA_POR_PRODUCTO DECIMAL(38,2) NOT NULL, PRODUCTO_ID INTEGER, SUBTOTAL_POR_PRODUCTO DECIMAL(38,2), NOMBRE_PRODUCTO VARCHAR(255), PRIMARY KEY (ID)) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IMAGEN_PRODUCTO (ID INTEGER NOT NULL AUTO_INCREMENT, ARCHIVO LONGBLOB, IMAGEN LONGBLOB, PRIMARY KEY (ID)) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE INGRESOS_EGRESOS (EGRESOS DECIMAL(38,2), ID INTEGER NOT NULL AUTO_INCREMENT, INGRESOS DECIMAL(38,2), FECHA DATETIME(6), DETALLE VARCHAR(512), PRIMARY KEY (ID)) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE INVENTARIO (ENTRADAS INTEGER, EXISTENCIA INTEGER, ID INTEGER NOT NULL AUTO_INCREMENT, PRODUCTO_ID INTEGER, SALDO_ANTERIOR INTEGER, SALIDAS INTEGER, FECHA DATETIME(6), PRIMARY KEY (ID)) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE PRODUCTO (COSTO_UNIDAD DECIMAL(38,2) NOT NULL, EXISTENCIAS INTEGER NOT NULL, GANANCIA DECIMAL(38,2) NOT NULL, ID INTEGER NOT NULL AUTO_INCREMENT, PRECIO_VENTA DECIMAL(38,2) NOT NULL, FECHA_ADQUISICION DATETIME(6), FECHA_MODIFICADO DATETIME(6), NOMBRE VARCHAR(512) NOT NULL, PRIMARY KEY (ID)) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE USUARIO (ID INTEGER NOT NULL AUTO_INCREMENT, PENDIENTE_DE_PAGO DECIMAL(38,2) NOT NULL, COMENTARIOS VARCHAR(512), APELLIDO VARCHAR(255), APELLIDO_DOS VARCHAR(255), NOMBRE VARCHAR(255) NOT NULL, NOMBRE_COMPLETO VARCHAR(255), NOMBRE_DOS VARCHAR(255), PRIMARY KEY (ID)) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE  PRODUCTO ADD CONSTRAINT UK_9SU14N91MTGCG5EHL658V4AFX UNIQUE (NOMBRE);
ALTER TABLE  CLIENTE_ABONA ADD CONSTRAINT FK7PX57P1VLVGQVSK7HY3LJGENC FOREIGN KEY (USUARIO_ID) REFERENCES  USUARIO (ID);
ALTER TABLE  CLIENTE_ABONA ADD CONSTRAINT FK87VEI7J6JLRBU2JAOSY9CNCJH FOREIGN KEY (FACTURA_ID) REFERENCES  FACTURA (ID);
ALTER TABLE  FACTURA ADD CONSTRAINT FKARQ3CR11IIEGH05DE5TY51BMT FOREIGN KEY (USUARIO_ID) REFERENCES  USUARIO (ID);
ALTER TABLE  FACTURA_DETALLE ADD CONSTRAINT FK82G5TPB19DN0ED3DH8RJEPFEO FOREIGN KEY (FACTURA_ID) REFERENCES  FACTURA (ID);
ALTER TABLE  FACTURA_DETALLE ADD CONSTRAINT FK49CXXXB69HBP79OT7Q72D1AMT FOREIGN KEY (PRODUCTO_ID) REFERENCES  PRODUCTO (ID);
ALTER TABLE  INVENTARIO ADD CONSTRAINT FK2JPMJSXWL42BLFEA24VDA6FS6 FOREIGN KEY (PRODUCTO_ID) REFERENCES  PRODUCTO (ID);

CREATE TABLE TABLAA(ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID), NOMBRE VARCHAR ) ENGINE=INNODB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ; 
